name: Post welcome comment
on:
#indicates that the workflow will execute anytime a pull request opens in the repository 
  pull_request:
    types: [opened]
    # gives the workflow permission to write to pull requests. This is needed to create the welcome comment.
permissions:
  pull-requests: write
jobs:
  build:
    name:Post welcome comment
    runs:ubuntu_latest
      steps:
        - run: gh pr comment $PR_URL --body "Welcome to the repository!"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_URL: ${{ github.event.pull_request.html_url }}
